### ISSUE TITLE
Missing arguments for get_scoreboard_maps

### ISSUE THREAD

**Issue by williamtfalch** [Sbosvk/crcon.js#3]
We're missing ```page``` and ```page_size``` arguments in the ```get_scoreboard_maps``` method

**Comment by Sbosvk** [comment]
Thank you for creating this issue. You are indeed correct. This interface is based on the documentation and this particular endpoint is missing arguments there. I will push a patch shortly.

**Comment by Sbosvk** [comment]
I have been running some tests and it appears that `page_size` is not an accepted argument for this endpoint and will always regardless default to 100.

**Comment by Sbosvk** [comment]
Closing this issue as fix has been published. Thank you again for reporting this.

**Comment by Sbosvk** [comment]
Closing this issue as fix has been published. Thank you again for reporting this.

**Comment by williamtfalch** [comment]
Thanks for sorting it :)
